import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { jsonFiles, readJson, root } from "./library.mjs";

const recipeFiles = await jsonFiles(path.join(root, "recipes"));
const ingredientFiles = await jsonFiles(path.join(root, "ingredients"));
const recipes = await Promise.all(recipeFiles.map(readJson));
const ingredients = await Promise.all(ingredientFiles.map(readJson));
const generatedAt = new Date().toISOString();
const catalog = { schema_version: "1.0.0", generated_at: generatedAt, recipes, ingredients };

await mkdir(path.join(root, "app/generated"), { recursive: true });
await mkdir(path.join(root, "public/data"), { recursive: true });
await writeFile(
  path.join(root, "app/generated/catalog.ts"),
  `// Generated by npm run catalog:build. Do not edit by hand.\nexport const catalog = ${JSON.stringify(catalog, null, 2)} as const;\n`,
);
await writeFile(path.join(root, "public/data/catalog.json"), `${JSON.stringify(catalog, null, 2)}\n`);
console.log(`Catalog built with ${recipes.length} recipes and ${ingredients.length} ingredients.`);
